// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {PersonId} from "./PersonId";

/**
 * Add a moderator to a category.
 */
export type AddModToCategory = {
  categoryId: CategoryId;
  personId: PersonId;
  added: boolean;
};
