// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryModeratorView} from "./CategoryModeratorView";

/**
 * The response of adding a moderator to a category.
 */
export type AddModToCategoryResponse = {
  moderators: Array<CategoryModeratorView>;
};
