// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryView} from "./CategoryView";

/**
 * The block category response.
 */
export type BlockCategoryResponse = {
  categoryView: CategoryView;
  blocked: boolean;
};
