// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryView} from "./CategoryView";
import type {LanguageId} from "./LanguageId";

/**
 * A simple category response.
 */
export type CategoryResponse = {
  categoryView: LanguageId;
  discussionLanguages: Array<LanguageId>;
};
