// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {TagsView} from "./TagsView";

/**
 * A category view.
 */
export type CategoryView = {
    category: Category;
    canMod: boolean;
    postTags: TagsView;
};
