// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {InstanceActions} from "./InstanceActions";
import type {TagsView} from "./TagsView";
import {CategoryActions} from "./CategoryActions";

/**
 * A category view.
 */
export type CategoryView = {
    category: Category;
    categoryActions?: CategoryActions;
    instanceActions?: InstanceActions;
    canMod: boolean;
    postTags: TagsView;
};
