// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Comment} from "./Comment";
import type {Category} from "./Category";
import type {Person} from "./Person";
import type {Post} from "./Post";
import type {TagsView} from "./TagsView";

/**
 * A proposal view (formerly CommentView — backend calls this ProposalView).
 */
export type CommentView = {
    proposal: Comment;
    creator: Person;
    post: Post;
    category: Category;
    creatorIsAdmin: boolean;
    postTags: TagsView;
    canMod: boolean;
    creatorBanned: boolean;
    creatorIsModerator: boolean;
    creatorBannedFromCategory: boolean;
};
