// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryModeratorView} from "./CategoryModeratorView";

/**
 * The category response.
 */
export type GetCategoryResponse = {
  moderators: Array<CategoryModeratorView>;
};
