// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryModeratorView} from "./CategoryModeratorView";
import type {PersonView} from "./PersonView";
import type {Site} from "./Site";

/**
 * A person's details response.
 */
export type GetPersonDetailsResponse = {
  personView: PersonView;
  site?: Site;
  moderates: Array<CategoryModeratorView>;
};
