// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountView} from "./BankAccountView";
import {PaginationCursor} from "./PaginationCursor";

/**
 * List bank accounts.
 */
export type ListBankAccountsResponse = {
    bankAccounts: Array<BankAccountView>,
    nextPage?: PaginationCursor,
    prevPage?: PaginationCursor
};
