// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentSortType} from "./CommentSortType";
import type {ListingType} from "./ListingType";
import type {LocalSiteId} from "./LocalSiteId";
import type {PersonId} from "./PersonId";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {RegistrationMode} from "./RegistrationMode";
import type {SiteId} from "./SiteId";

/**
 * The local site.
 */
export type LocalSite = {
  id: LocalSiteId;
  siteId: SiteId;
  /**
   * True if the site is set up.
   */
  siteSetup: boolean;
  /**
   * Whether only admins can create categories.
   */
  categoryCreationAdminOnly: boolean;
  /**
   * Whether emails are required.
   */
  requireEmailVerification: boolean;
  /**
   * Whether the instance is private or public.
   */
  privateInstance: boolean;
  /**
   * The default front-end theme.
   */
  defaultTheme: string;
  defaultPostListingType: ListingType;
  /**
   * An optional legal disclaimer page.
   */
  legalInformation?: string;
  /**
   * An optional regex to filter words.
   */
  slurFilterRegex?: string;
  /**
   * The max actor name length.
   */
  actorNameMaxLength: number;
  /**
   * Whether captcha is enabled.
   */
  captchaEnabled: boolean;
  /**
   * The captcha difficulty.
   */
  captchaDifficulty: string;
  publishedAt: string;
  updatedAt?: string;
  registrationMode: RegistrationMode;
  /**
   * Default value for [LocalSite.post_listing_mode]
   */
  defaultPostListingMode: PostListingMode;
  /**
   * Default value for [LocalUser.post_sort_type]
   */
  defaultPostSortType: PostSortType;
  /**
   * Default value for [LocalUser.comment_sort_type]
   */
  defaultCommentSortType: CommentSortType;
  /**
   * Whether or not external auth methods can auto-register users.
   */
  oauthRegistration: boolean;
  /**
   * A default time range limit to apply to post sorts, in seconds.
   */
  defaultPostTimeRangeSeconds?: number;
  /**
   * Block NSFW content being created
   */
  disallowNsfwContent: boolean;
  users: number;
  posts: number;
  comments: number;
  categories: number;
  /**
   * The number of users with any activity in the last day.
   */
  usersActiveDay: number;
  /**
   * The number of users with any activity in the last week.
   */
  usersActiveWeek: number;
  /**
   * The number of users with any activity in the last month.
   */
  usersActiveMonth: number;
  /**
   * The number of users with any activity in the last half year.
   */
  usersActiveHalfYear: number;
  /**
   * Dont send email notifications to users for new replies, mentions etc
   */
  disableEmailNotifications: boolean;
  multiCommFollower: PersonId;
};
