// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ImageDetails} from "./ImageDetails";
import type {Person} from "./Person";
import type {Post} from "./Post";
import type {TagsView} from "./TagsView";

/**
 * A post view.
 */
export type PostView = {
    post: Post;
    creator: Person;
    category: Category;
    imageDetails?: ImageDetails;
    creatorIsAdmin: boolean;
    tags: TagsView;
    canMod: boolean;
    creatorBanned: boolean;
    creatorIsModerator: boolean;
    creatorBannedFromCategory: boolean;
};
