// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AdminPurgeCategoryId} from "./AdminPurgeCategoryId";
import type {PersonId} from "./PersonId";

/**
 * When an admin purges a category.
 */
export type AdminPurgeCategory = {
  id: AdminPurgeCategoryId;
  adminPersonId: PersonId;
  reason?: string;
  publishedAt: string;
};
