// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AdminPurgeCategory} from "./AdminPurgeCategory";
import type {Person} from "./Person";

/**
 * When an admin purges a category.
 */
export type AdminPurgeCategoryView = {
  adminPurgeCategory: AdminPurgeCategory;
  admin?: Person;
};
