// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AdminPurgePostId} from "./AdminPurgePostId";
import type {CategoryId} from "./CategoryId";
import type {PersonId} from "./PersonId";

/**
 * When an admin purges a post.
 */
export type AdminPurgePost = {
  id: AdminPurgePostId;
  adminPersonId: PersonId;
  categoryId: CategoryId;
  reason?: string;
  publishedAt: string;
};
