// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryReportView} from "./CategoryReportView";

/**
 * A category report response.
 */
export type CategoryReportResponse = {
  categoryReportView: CategoryReportView;
};
