// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {CategoryReport} from "./CategoryReport";
import type {Person} from "./Person";

/**
 * A category report view.
 */
export type CategoryReportView = {
    categoryReport: CategoryReport;
    category: Category;
    creator: Person;
    resolver?: Person;
    creatorIsAdmin: boolean;
    creatorIsModerator: boolean;
    creatorBanned: boolean;
    creatorBannedFromCategory: boolean;
};
