// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryReportId} from "./CategoryReportId";
import type {PersonId} from "./PersonId";
import {CategoryId} from "./CategoryId";

/**
 * A comment report.
 */
export type CategoryReport = {
    id: CategoryReportId;
    creatorId: PersonId;
    categoryId: CategoryId;
    originalCategoryName: string;
    originalCategoryTitle: string;
    originalCategoryDescription?: string;
    originalCategorySidebar?: string;
    originalCategoryIcon?: string;
    originalCategoryBanner?: string;
    reason: string;
    resolved: boolean;
    resolverId?: PersonId;
    publishedAt: string;
    updatedAt?: string;
};
