// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The category sort types. See here for descriptions: https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html
 */
export type CategorySortType =
  | "ActiveSixMonths"
  | "ActiveMonthly"
  | "ActiveWeekly"
  | "ActiveDaily"
  | "Hot"
  | "New"
  | "Old"
  | "NameAsc"
  | "NameDesc"
  | "Comments"
  | "Posts"
  | "Subscribers"
  | "SubscribersLocal";
