// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Person} from "./Person";
import {Category} from "./Category";

/**
 * A category follower.
 */
export type CategoryFollowerView = { category: Category; follower: Person };
