// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Parameter for setting category icon or banner. Can't use POST data here as it already contains
 * the image data.
 */
export type CategoryIdQuery = {
  id: CategoryId;
};
