// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Comment} from "./Comment";
import type {CommentActions} from "./CommentActions";
import type {CommentReport} from "./CommentReport";
import type {Category} from "./Category";
import type {CategoryActions} from "./CategoryActions";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {Post} from "./Post";

/**
 * A comment report view.
 */
export type CommentReportView = {
    commentReport: CommentReport;
    comment: Comment;
    post: Post;
    category: Category;
    creator: Person;
    commentCreator: Person;
    commentActions?: CommentActions;
    resolver?: Person;
    personActions?: PersonActions;
    categoryActions?: CategoryActions;
    creatorIsAdmin: boolean;
    creatorIsModerator: boolean;
    creatorBanned: boolean;
    creatorBannedFromCategory: boolean;
};
