// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentView} from "./CommentView";

/**
 * A proposal response (backend field is proposalView).
 */
export type CommentResponse = {
  proposalView: CommentView;
};
