// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Create a report for a category.
 */
export type CreateCategoryReport = {
  categoryId: CategoryId;
  reason: string;
};
