// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {CategoryVisibility} from "./CategoryVisibility";
import type {LanguageId} from "./LanguageId";

/**
 * Edit a category.
 */
export type EditCategory = {
    categoryId: CategoryId;
    /**
     * A longer title.
     */
    title?: string;
    /**
     * A sidebar for the category in markdown.
     */
    sidebar?: string;
    /**
     * A shorter, one line description of your category.
     */
    description?: string;
    /**
     * Whether its an NSFW category.
     */
    nsfw?: boolean;
    /**
     * Whether to restrict posting only to moderators.
     */
    postingRestrictedToMods?: boolean;
    discussionLanguages?: Array<LanguageId>;
    visibility?: CategoryVisibility;
};
