// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Federation related errors, these dont need to be translated.
 */
export type FederationError =
  | "InvalidCategory"
  | "CannotCreatePostOrCommentInDeletedOrRemovedCategory"
  | "CannotReceivePage"
  | "OnlyLocalAdminCanRemoveCategory"
  | "OnlyLocalAdminCanRestoreCategory"
  | "PostIsLocked"
  | {PersonIsBannedFromSite: string}
  | "InvalidVoteValue"
  | "PageDoesNotSpecifyCreator"
  | "CouldntGetComments"
  | "CouldntGetPosts"
  | "FederationDisabled"
  | {DomainBlocked: string}
  | {DomainNotInAllowList: string}
  | "FederationDisabledByStrictAllowList"
  | "ContradictingFilters"
  | "UrlWithoutDomain"
  | "InboxTimeout"
  | "CantDeleteSite"
  | "ObjectIsNotPublic"
  | "ObjectIsNotPrivate"
  | "PlatformLackingPrivateCategorySupport"
  | "Unreachable";
