// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Follow / subscribe to a category.
 */
export type FollowCategory = {
  categoryId: CategoryId;
};
