// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryModeratorView} from "./CategoryModeratorView";
import type {LanguageId} from "./LanguageId";
import type {Site} from "./Site";

/**
 * The category response.
 */
export type GetCategoryResponse = {
  site?: Site;
  moderators: Array<CategoryModeratorView>;
  discussionLanguages: Array<LanguageId>;
};
