// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentView} from "./CommentView";
import type {PaginationCursor} from "./PaginationCursor";

/**
 * The proposal list response (backend field is 'proposals').
 */
export type GetCommentsResponse = {
  proposals: Array<CommentView>;
  nextPage?: PaginationCursor;
  prevPage?: PaginationCursor;
};
