// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryView} from "./CategoryView";
import type {PostView} from "./PostView";

/**
 * The post response.
 */
export type GetPostResponse = {
  postView: PostView;
  categoryView: CategoryView;
  /**
   * A list of cross-posts, or other times / categories this link has been posted to.
   */
  crossPosts: Array<PostView>;
};
