// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Hide a category from the main view.
 */
export type HideCategory = {
    categoryId: CategoryId;
    hidden: boolean;
    reason?: string;
};
