// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {CategoryNodeView} from "./CategoryNodeView";


/**
 * The response for listing categories.
 */
export interface ListCategoriesTreeResponse {
    categories: CategoryNodeView[];
    count: number;
}
