// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type {PaginationCursor} from "./PaginationCursor";
import {CategoryNodeView} from "./CategoryNodeView";

/**
 * The response for listing categories.
 */
export type ListCategoriesResponse = {
  categories: Array<CategoryNodeView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  nextPage?: PaginationCursor;
  prevPage?: PaginationCursor;
};
