// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModAddCategory} from "./ModAddCategory";
import type {Person} from "./Person";

/**
 * When someone is added as a category moderator.
 */
export type ModAddCategoryView = {
  modAddCategory: ModAddCategory;
  moderator?: Person;
  category: Category;
  otherPerson: Person;
};
