// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {ModAddCategoryId} from "./ModAddCategoryId";
import type {PersonId} from "./PersonId";

/**
 * When someone is added as a category moderator.
 */
export type ModAddCategory = {
    id: ModAddCategoryId;
    modPersonId: PersonId;
    otherPersonId: PersonId;
    categoryId: CategoryId;
    removed: boolean;
    publishedAt: string;
};
