// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModBanFromCategory} from "./ModBanFromCategory";
import type {Person} from "./Person";

/**
 * When someone is banned from a category.
 */
export type ModBanFromCategoryView = {
  modBanFromCategory: ModBanFromCategory;
  moderator?: Person;
  category: Category;
  otherPerson: Person;
};
