// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {ModBanFromCategoryId} from "./ModBanFromCategoryId";
import type {PersonId} from "./PersonId";

/**
 * When someone is banned from a category.
 */
export type ModBanFromCategory = {
  id: ModBanFromCategoryId;
  modPersonId: PersonId;
  otherPersonId: PersonId;
  categoryId: CategoryId;
  reason?: string;
  banned: boolean;
  expiresAt?: string;
  publishedAt: string;
};
