// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModChangeCategoryVisibility} from "./ModChangeCategoryVisibility";
import type {Person} from "./Person";

/**
 * When the visibility of a category is changed
 */
export type ModChangeCategoryVisibilityView = {
  modChangeCategoryVisibility: ModChangeCategoryVisibility;
  moderator?: Person;
  category: Category;
};
