// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {CategoryVisibility} from "./CategoryVisibility";
import type {ModChangeCategoryVisibilityId} from "./ModChangeCategoryVisibilityId";
import type {PersonId} from "./PersonId";

export type ModChangeCategoryVisibility = {
  id: ModChangeCategoryVisibilityId;
  categoryId: CategoryId;
  modPersonId: PersonId;
  publishedAt: string;
  visibility: CategoryVisibility;
};
