// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModFeaturePost} from "./ModFeaturePost";
import type {Person} from "./Person";
import type {Post} from "./Post";

/**
 * When a moderator features a post on a category (pins it to the top).
 */
export type ModFeaturePostView = {
  modFeaturePost: ModFeaturePost;
  moderator?: Person;
  otherPerson: Person;
  post: Post;
  category: Category;
};
