// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModLockPost} from "./ModLockPost";
import type {Person} from "./Person";
import type {Post} from "./Post";

/**
 * When a moderator locks a post (prevents new comments being made).
 */
export type ModLockPostView = {
  modLockPost: ModLockPost;
  moderator?: Person;
  otherPerson: Person;
  post: Post;
  category: Category;
};
