// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A list of possible types for the various modlog actions.
 */
export type ModlogActionType =
  | "All"
  | "ModRemovePost"
  | "ModLockPost"
  | "ModFeaturePost"
  | "ModRemoveComment"
  | "ModRemoveCategory"
  | "ModBanFromCategory"
  | "ModAddCategory"
  | "ModTransferCategory"
  | "ModAdd"
  | "ModBan"
  | "ModChangeCategoryVisibility"
  | "AdminPurgePerson"
  | "AdminPurgeCategory"
  | "AdminPurgePost"
  | "AdminPurgeComment"
  | "AdminBlockInstance"
  | "AdminAllowInstance";
