// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AdminAllowInstanceView} from "./AdminAllowInstanceView";
import type {AdminBlockInstanceView} from "./AdminBlockInstanceView";
import type {AdminPurgeCommentView} from "./AdminPurgeCommentView";
import type {AdminPurgeCategoryView} from "./AdminPurgeCategoryView";
import type {AdminPurgePersonView} from "./AdminPurgePersonView";
import type {AdminPurgePostView} from "./AdminPurgePostView";
import type {ModAddCategoryView} from "./ModAddCategoryView";
import type {ModAddView} from "./ModAddView";
import type {ModBanFromCategoryView} from "./ModBanFromCategoryView";
import type {ModBanView} from "./ModBanView";
import type {ModChangeCategoryVisibilityView} from "./ModChangeCategoryVisibilityView";
import type {ModFeaturePostView} from "./ModFeaturePostView";
import type {ModLockPostView} from "./ModLockPostView";
import type {ModRemoveCommentView} from "./ModRemoveCommentView";
import type {ModRemoveCategoryView} from "./ModRemoveCategoryView";
import type {ModRemovePostView} from "./ModRemovePostView";
import type {ModTransferCategoryView} from "./ModTransferCategoryView";

export type ModlogCombinedView =
    | ({ type_: "AdminAllowInstance" } & AdminAllowInstanceView)
    | ({ type_: "AdminBlockInstance" } & AdminBlockInstanceView)
    | ({ type_: "AdminPurgeComment" } & AdminPurgeCommentView)
    | ({ type_: "AdminPurgeCategory" } & AdminPurgeCategoryView)
    | ({ type_: "AdminPurgePerson" } & AdminPurgePersonView)
    | ({ type_: "AdminPurgePost" } & AdminPurgePostView)
    | ({ type_: "ModAdd" } & ModAddView)
    | ({ type_: "ModAddCategory" } & ModAddCategoryView)
    | ({ type_: "ModBan" } & ModBanView)
    | ({ type_: "ModBanFromCategory" } & ModBanFromCategoryView)
    | ({ type_: "ModFeaturePost" } & ModFeaturePostView)
    | ({
    type_: "ModChangeCategoryVisibility";
} & ModChangeCategoryVisibilityView)
    | ({ type_: "ModLockPost" } & ModLockPostView)
    | ({ type_: "ModRemoveComment" } & ModRemoveCommentView)
    | ({ type_: "ModRemoveCategory" } & ModRemoveCategoryView)
    | ({ type_: "ModRemovePost" } & ModRemovePostView)
    | ({ type_: "ModTransferCategory" } & ModTransferCategoryView);
