// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModRemovePost} from "./ModRemovePost";
import type {Person} from "./Person";
import type {Post} from "./Post";

/**
 * When a moderator removes a post.
 */
export type ModRemovePostView = {
    modRemovePost: ModRemovePost;
    moderator?: Person;
    otherPerson: Person;
    post: Post;
    category: Category;
};
