// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {ModRemoveCategoryId} from "./ModRemoveCategoryId";
import type {PersonId} from "./PersonId";

/**
 * When a moderator removes a category.
 */
export type ModRemoveCategory = {
    id: ModRemoveCategoryId;
    modPersonId: PersonId;
    categoryId: CategoryId;
    reason?: string;
    removed: boolean;
    publishedAt: string;
};
