// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModRemoveCategory} from "./ModRemoveCategory";
import type {Person} from "./Person";

/**
 * When a moderator removes a category.
 */
export type ModRemoveCategoryView = {
    modRemoveCategory: ModRemoveCategory;
    moderator?: Person;
    category: Category;
};
