// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ModTransferCategory} from "./ModTransferCategory";
import type {Person} from "./Person";

/**
 * When a moderator transfers a category to a new owner.
 */
export type ModTransferCategoryView = {
  modTransferCategory: ModTransferCategory;
  moderator?: Person;
  category: Category;
  otherPerson: Person;
};
