// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {ModTransferCategoryId} from "./ModTransferCategoryId";
import type {PersonId} from "./PersonId";

/**
 * When a moderator transfers a category to a new owner.
 */
export type ModTransferCategory = {
    id: ModTransferCategoryId;
    modPersonId: PersonId;
    otherPersonId: PersonId;
    categoryId: CategoryId;
    publishedAt: string;
};
