// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {CategoryFollowerState} from "./CategoryFollowerState";
import type {Person} from "./Person";

export type PendingFollow = {
    person: Person;
    category: Category;
    isNewInstance: boolean;
    followState?: CategoryFollowerState;
};
