// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {CategoryActions} from "./CategoryActions";
import type {ImageDetails} from "./ImageDetails";
import type {InstanceActions} from "./InstanceActions";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {PersonPostMention} from "./PersonPostMention";
import type {Post} from "./Post";
import type {PostActions} from "./PostActions";
import type {TagsView} from "./TagsView";

/**
 * A person post mention view.
 */
export type PersonPostMentionView = {
  personPostMention: PersonPostMention;
  recipient: Person;
  post: Post;
  creator: Person;
  category: Category;
  imageDetails?: ImageDetails;
  categoryActions?: CategoryActions;
  personActions?: PersonActions;
  postActions?: PostActions;
  instanceActions?: InstanceActions;
  creatorHomeInstanceActions?: InstanceActions;
  creatorLocalInstanceActions?: InstanceActions;
  creatorCategoryActions?: CategoryActions;
  postTags: TagsView;
  creatorIsAdmin: boolean;
  canMod: boolean;
  creatorBanned: boolean;
};
