// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Purges a category from the database. This will delete all content attached to that category.
 */
export type PurgeCategory = {
  categoryId: CategoryId;
};
