// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Remove a category (only doable by moderators).
 */
export type RemoveCategory = {
  categoryId: CategoryId;
  removed: boolean;
  reason?: string;
};
