// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryReportId} from "./CategoryReportId";

/**
 * Resolve a category report.
 */
export type ResolveCategoryReport = {
  reportId: CategoryReportId;
  resolved: boolean;
};
