// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {DbUrl} from "./DbUrl";
import type {TagId} from "./TagId";

/**
 * A tag that can be assigned to a post within a category.
 * The tag object is created by the category moderators.
 * The assignment happens by the post creator and can be updated by the category moderators.
 *
 * A tag is a federatable object that gives additional context to another object, which can be
 * displayed and filtered on. Currently, we only have category post tags, which is a tag that is
 * created by the mods of a category, then assigned to posts by post authors as well as mods of a
 * category, to categorize a post.
 *
 * In the future we may add more tag types, depending on the requirements, this will lead to either
 * expansion of this table (category_id optional, addition of tag_type enum) or split of this
 * table / creation of new tables.
 */
export type Tag = {
  id: TagId;
  apId: DbUrl;
  displayName: string;
  /**
   * the category that owns this tag
   */
  categoryId: CategoryId;
  publishedAt: string;
  updatedAt?: string;
  deleted: boolean;
};
