// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {PersonId} from "./PersonId";

/**
 * Transfer a category to a new owner.
 */
export type TransferCategory = {
  categoryId: CategoryId;
  personId: PersonId;
};
