// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {CategoryNotificationsMode} from "./CategoryNotificationsMode";

/**
 * Change notification settings for a category
 */
export type UpdateCategoryNotifications = {
  categoryId: CategoryId;
  mode: CategoryNotificationsMode;
};
